spring:
  rabbitmq:
    addresses: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  mail:
    host: smtp.qq.com
    protocol: smtp
    default-encoding: UTF-8
    password: qgrxmkxpwiidfdgd
    username: 1939136076@qq.com
    port: 25